const fs = require('fs');

let i18n = fs.readFileSync('src/lib/i18n.tsx', 'utf8');

const slovakAnom = `    "anom.zeroWidth": "Nulová šírka znaku",
    "anom.emptyGlyph": "Prázdny glyf",
    "anom.islands": "Malé izolované časti",
    "anom.complex": "Prekrývajúce sa alebo zložité cesty",
    "anom.overlap": "Diakritika sa prekrýva so základným znakom",
    "anom.heightLower": "Malé písmeno má nesprávnu výšku (chová sa ako veľké)",
    "anom.heightUpper": "Veľké písmeno má nesprávnu výšku",
    "anom.narrow": "Príliš úzke bočné medzery (presah)",
    "alert.loadError": "Nepodarilo sa načítať font: Súbor pravdepodobne nie je platný font (môže ísť o obrázok alebo iný formát).",
    "alert.woff2": "Formát WOFF2 nie je plne podporovaný. Prosím, prekonvertujte font na TTF alebo OTF.",
    "alert.loadFailed": "Nepodarilo sa načítať font: {msg}. Uistite sa, že ide o platný súbor TTF, OTF alebo UFONT.",
    "alert.bulkDeployError": "Chyba pri hromadnom nasadení.",
    "alert.invalidJson": "Neplatný JSON súbor.",
    "alert.exportFailed": "Nepodarilo sa exportovať font. Pozrite si konzolu pre viac detailov.",
    "alert.saveDiacriticError": "Chyba pri ukladaní diakritiky: {msg}",
    "prompt.diacriticName": "Zadajte názov pre diakritiku:",
    "canvas.optHeight": "OPTIMÁLNA VÝŠKA",
    "canvas.lower": "Malé písmená",
    "canvas.upper": "Veľké písmená",
    "app.dropHere": "Kliknite alebo potiahnite súbory pre nahratie fontov",
    "app.confirmDeleteHistory": "Naozaj chcete vymazať celú históriu projektov? Táto akcia je nevratná.",
    "app.closeProject": "Zavrieť projekt a vrátiť sa na úvodnú obrazovku",
    "app.logo": "Logo aplikácie",
    "app.loadedFont": "Aktuálne načítaný font",
    "app.unsavedChanges": "Neuložené zmeny (automatické ukladanie prebieha...)",
    "app.undo": "Krok späť (podržte pre rýchly návrat)",
    "app.redo": "Krok vpred (podržte pre rýchly posun)",
    "app.loadSettings": "Načítať predtým uložené nastavenia diakritiky z JSON súboru",
    "app.applyVariants": "Aplikovať zmeny na všetky nahrané rezy fontu (Bold, Italic, atď.)",
    "app.saveSettings": "Uložiť aktuálne nastavenia diakritiky do JSON súboru",
    "app.downloadFont": "Vygenerovať a stiahnuť upravený font (experimentálne)",
    "app.statusUnknown": "Neznámy stav",
    "app.statusMissing": "Chýba základ alebo zdroj",
    "app.recenterView": "Vrátiť pohľad na stred",
    "app.previewAll": "Všetky",
    "app.previewHeading": "Nadpis",
    "app.previewBody": "Bežný",
    "app.previewMicro": "Micro",
    "app.editPreview": "Upraviť náhľadový text",
    "app.autoMerge": "Automaticky zlúčiť prekrývajúce sa cesty a vyčistiť tvar",
    "app.useOriginal": "Použiť pôvodný glyf priamo z fontu",
    "app.pov": "Pôv",
    "app.krad": "Krad",
    "app.addToLib": "Pridať aktuálnu diakritiku do knižnice",
    "app.scaleDesc": "Aplikovať zmenšenie na všetky malé písmená s diakritikou (ľ, š, č, ť, ž, ň, ď, ě, ř, ô, ů, ä)",
    "app.scaleAll": "Celkové zväčšenie/zmenšenie",
    "app.moveH": "Horizontálny posun",
    "app.moveV": "Vertikálny posun",
    "app.rotateDeg": "Otočenie v stupňoch",
    "app.flipH": "Zrkadlovo otočiť horizontálne",
    "app.flipV": "Zrkadlovo otočiť vertikálne",
    "app.scaleH": "Horizontálne zväčšenie/zmenšenie",
    "app.scaleV": "Vertikálne zväčšenie/zmenšenie",
    "app.skewHDeg": "Horizontálne skosenie (naklonenie) v stupňoch",
    "app.skewVDeg": "Vertikálne skosenie v stupňoch",
    "app.propAnalysis": "Analýza proporcií a kerningu",
    "app.libDesc": "Knižnica uložených diakritických znamienok",
    "app.applyTarget": "Použiť toto znamienko na vybraný znak",
    "app.totalWidth": "Celková šírka znaku (určuje, kde začne ďalší znak)",
    "app.eraseAll": "Vymazať všetky ťahy gumou pre tento znak",
`;

const czechAnom = `    "anom.zeroWidth": "Nulová šířka znaku",
    "anom.emptyGlyph": "Prázdný glyf",
    "anom.islands": "Malé izolované části",
    "anom.complex": "Překrývající se nebo složité cesty",
    "anom.overlap": "Diakritika se vertikálně překrývá se základním znakem",
    "anom.heightLower": "Malé písmeno má nesprávnou výšku (chová se jako velké)",
    "anom.heightUpper": "Velké písmeno má nesprávnou výšku",
    "anom.narrow": "Příliš úzké boční mezery (přesah)",
    "alert.loadError": "Nepodařilo se načíst font: Soubor pravděpodobně není platný font (může jít o obrázek nebo jiný formát).",
    "alert.woff2": "Formát WOFF2 není plně podporován. Prosím, zkonvertujte font na TTF nebo OTF.",
    "alert.loadFailed": "Nepodařilo se načíst font: {msg}. Ujistěte se, že jde o platný soubor TTF, OTF nebo UFONT.",
    "alert.bulkDeployError": "Chyba při hromadném nasazení.",
    "alert.invalidJson": "Neplatný JSON soubor.",
    "alert.exportFailed": "Nepodařilo se exportovat font. Podívejte se do konzole pro více detailů.",
    "alert.saveDiacriticError": "Chyba při ukládání diakritiky: {msg}",
    "prompt.diacriticName": "Zadejte název pro diakritiku:",
    "canvas.optHeight": "OPTIMÁLNÍ VÝŠKA",
    "canvas.lower": "Malá písmena",
    "canvas.upper": "Velká písmena",
    "app.dropHere": "Klikněte nebo přetáhněte soubory pro nahrání fontů",
    "app.confirmDeleteHistory": "Opravdu chcete vymazat celou historii projektů? Tato akce je nevratná.",
    "app.closeProject": "Zavřít projekt a vrátit se na úvodní obrazovku",
    "app.logo": "Logo aplikace",
    "app.loadedFont": "Aktuálně načtený font",
    "app.unsavedChanges": "Neuložené změny (automatické ukládání probíhá...)",
    "app.undo": "Krok zpět (podržte pro rychlý návrat)",
    "app.redo": "Krok vpřed (podržte pro rychlý posun)",
    "app.loadSettings": "Načíst dříve uložené nastavení diakritiky z JSON souboru",
    "app.applyVariants": "Aplikovat změny na všechny nahrané řezy fontu (Bold, Italic, atd.)",
    "app.saveSettings": "Uložit aktuální nastavení diakritiky do JSON souboru",
    "app.downloadFont": "Vygenerovat a stáhnout upravený font (experimentální)",
    "app.statusUnknown": "Neznámý stav",
    "app.statusMissing": "Chybí základ nebo zdroj",
    "app.recenterView": "Vrátit pohled na střed",
    "app.previewAll": "Všechny",
    "app.previewHeading": "Nadpis",
    "app.previewBody": "Běžný",
    "app.previewMicro": "Micro",
    "app.editPreview": "Upravit náhledový text",
    "app.autoMerge": "Automaticky sloučit překrývající se cesty a vyčistit tvar",
    "app.useOriginal": "Použít původní glyf přímo z fontu",
    "app.pov": "Pův",
    "app.krad": "Krad",
    "app.addToLib": "Přidat aktuální diakritiku do knihovny",
    "app.scaleDesc": "Aplikovat zmenšení na všechna malá písmena s diakritikou (ľ, š, č, ť, ž, ň, ď, ě, ř, ô, ů, ä)",
    "app.scaleAll": "Celkové zvětšení/zmenšení",
    "app.moveH": "Horizontální posun",
    "app.moveV": "Vertikální posun",
    "app.rotateDeg": "Otočení ve stupních",
    "app.flipH": "Zrcadlově otočit horizontálně",
    "app.flipV": "Zrcadlově otočit vertikálně",
    "app.scaleH": "Horizontální zvětšení/zmenšení",
    "app.scaleV": "Vertikální zvětšení/zmenšení",
    "app.skewHDeg": "Horizontální zkosení (naklonění) ve stupních",
    "app.skewVDeg": "Vertikální zkosení ve stupních",
    "app.propAnalysis": "Analýza proporcí a kerningu",
    "app.libDesc": "Knihovna uložených diakritických znamének",
    "app.applyTarget": "Použít toto znaménko na vybraný znak",
    "app.totalWidth": "Celková šířka znaku (určuje, kde začne další znak)",
    "app.eraseAll": "Vymazat všechny tahy gumou pro tento znak",
`;

i18n = i18n.replace(
  /"preview\.stylistic": "Štýlová adaptácia \(Exp\.\)"/g,
  `"preview.stylistic": "Štýlová adaptácia (Exp.)",\n${slovakAnom}`
);

i18n = i18n.replace(
  /"preview\.stylistic": "Stylová adaptace \(Exp\.\)"/g,
  `"preview.stylistic": "Stylová adaptace (Exp.)",\n${czechAnom}`
);

fs.writeFileSync('src/lib/i18n.tsx', i18n);

console.log("i18n updated with anomaly and alert keys");

